rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aA*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aB*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aC*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aD*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aE*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aF*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aG*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aH*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aI*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aJ*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aK*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aL*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aM*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aN*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aO*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aP*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aQ*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aR*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aS*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aT*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aU*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aV*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aW*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aX*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aY*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Template~3aZ*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/A*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/B*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/C*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/D*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/E*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/F*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/G*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/H*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/I*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/J*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/K*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/L*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/M*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/N*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/O*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/P*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Q*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/R*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/S*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/T*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/U*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/V*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/W*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/X*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Y*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/Z*
rm /data/project/bambots/Bambots/cache/DatabaseReportBot/*
