#!/bin/bash
# Copyright 2022 Myers Enterprises II
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Kubernetes job creator with working directory
# Usage: ksub <working directory path or cwd or psub> jobname "command" <optional toolforge-jobs run parameters>
# Yaml usage: bin/ksub execute <working directory> command

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

case $1 in
	psub)
		WD=$PWD
		JOBNAME1=$2
		COMMAND1=$3
		shift 3
		
		JOBNAME="${JOBNAME1}-launch"
		COMMAND="php $SCRIPT_DIR/ksub.php $JOBNAME1 $COMMAND1 $@"
		set -- --cpu 250m
		;;
		
	cwd)
		WD=$PWD
		JOBNAME=$2
		COMMAND=$3
		shift 3
		;;
		
	execute)
		shift
		cd $1
		shift
		bash -c "$(printf ' %q' "$@")"
		
		exit
		;;
		
	*)
		WD=$1
		JOBNAME=$2
		COMMAND=$3
		shift 3
		;;
esac

toolforge-jobs run $JOBNAME --command "$SCRIPT_DIR/ksub execute $WD $COMMAND" --image tf-php74 $@
